# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: webquest_development
  pool: 5
  timeout: 5000
  username: Vera
  password: Vera

test:
  adapter: postgresql
  encoding: unicode
  database: webquest_test
  pool: 5
  timeout: 5000
  username: Vera
  password: Vera

production:
  adapter: postgresql
  encoding: unicode
  database: webquest_production
  pool: 5
  timeout: 5000
  username: Vera
  password: Vera